modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/MysticalAgriculture/issues"
    modId="mysticalagriculture"
    version="${file.jarVersion}"
    displayName="Mystical Agriculture"
    # updateJSONURL="http://myurl.me/"
    displayURL="https://blakesmods.com/mystical-agriculture"
    # logoFile="examplemod.png"
    authors="BlakeBr0"
    credits="Mark719, xun468, Cavemanrockx"
    description='''
    Grow all your resources!
    '''

    [[dependencies.mysticalagriculture]]
        modId="forge"
        mandatory=true
        versionRange="[47.1.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalagriculture]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.20.1]"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalagriculture]]
        modId="cucumber"
        mandatory=true
        versionRange="[7.0.2,)"
        ordering="NONE"
        side="BOTH"